### ISSUE TITLE
Cache tokenizer download between docker restarts

### ISSUE THREAD

**Issue by kbarto323** [3x3cut0r/docker#11]
Does running locally with Ollama need a separate tokenizer?  Each time the container starts it downloads:
privategpt    | Downloading LLM mistral-7b-instruct-v0.2.Q4_K_M.gguf

**Comment by 3x3cut0r** [comment]
I removed the setup in the docker entrypoint and added a new variable RUN_SETUP to be able to run the setup again if needed. default to false.
wait for the gitaction and try it out

**Comment by kbarto323** [comment]
Perfect, thank you!
