### ISSUE TITLE
Running Ollama on Windows host file upload error

### ISSUE THREAD

**Issue by kbarto323** [3x3cut0r/docker#12]
If I run Ollama on a docker container it appears to work, but when I run Ollama on the Windows host to leverage the GPU and upload a document, I get privategpt    | requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74b5469ca110>: Failed to establish a new connection: [Errno 111] Connection refused'))
I have changed the OLLAMA_API_BASE to the Windows host IP so it appears it isn't being updated everywhere it needs to be.

**Comment by 3x3cut0r** [comment]
i missed that privategpt added a new option "embedding_api_base" to the (settings-ollama.yaml)[https://github.com/zylon-ai/private-gpt/blob/main/settings-ollama.yaml]. i added OLLAMA_EMBEDDING_API_BASE to setup the api_base for the embedding.
you may now need to set both OLLAMA_API_BASE and OLLAMA_EMBEDDING_API_BASE to change the api base.
wait for the gitaction for my new version and try it out.

**Comment by kbarto323** [comment]
Excellent, thank you!
