### ISSUE TITLE
docker run from command line not working

### ISSUE THREAD

**Issue by niunmango** [3x3cut0r/docker#13]
After running with
```shell
docker run -d     --name privategpt     -p 8080:8080/tcp     3x3cut0r/privategpt:latest
```
Container starts but immediately stops. Logs say:
"
File "/home/worker/app/.venv/lib/python3.11/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Settings
openai.embedding_api_key
  Field required [type=missing, input_value={'api_base': 'https://api...model': 'gpt-3.5-turbo'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing

"

**Comment by 3x3cut0r** [comment]
i added the new setting parameters, which was missing.
can you try it again?

**Comment by niunmango** [comment]
Works perfectly now! Thanks!
