### ISSUE TITLE
Embedding Model duplicate in settings.yaml

### ISSUE THREAD

**Issue by kbarto323** [3x3cut0r/docker#14]
Getting an error uploading a doc saying model 5m not found - connected to container and found duplicate variable for embedding_model which I believe is supposed to be the timeout variable.

ollama:
  api_base: http://192.168.50.168:11434
  embedding_api_base: http://192.168.50.168:11434
  llm_model: llama3:latest
  embedding_model: all-minilm:l6-v2
  embedding_model: 5m
  tfs_z: 1.0
  num_predict: 128
  top_k: 40
  top_p: 0.9
  repeat_last_n: 64
  repeat_penalty: 1.1
  request_timeout: 120.0

**Comment by kbarto323** [comment]
That worked!  Thanks!

**Comment by 3x3cut0r** [comment]
yes, was a copy paste issue.
