### ISSUE TITLE
Using a username and password to get to the UI

### ISSUE THREAD

**Issue by dwesthead** [3x3cut0r/docker#21]
Hi,

Is the AUTH section of the environment for controlling access to the web UI ?

I have been asked to password protect it for now and I have set the AUTH_ENABLED: "true", AUTH_USERNAME: "<username>" and AUTH_SECRET: "Basic Z3B0dXNlcjpCdTFsZGFkbQ==" which is got from the python command.... but i never get prompted for any username or password ?

Dean.

**Comment by 3x3cut0r** [comment]
Hi, this is no issue due my docker image, but an upstream issue. And there is already an open issue about that, see: https://github.com/zylon-ai/private-gpt/issues/1899
