### ISSUE TITLE
missing docx2txt dependency for privategpt

### ISSUE THREAD

**Issue by JeremiahSecrist** [3x3cut0r/docker#3]
![image](https://github.com/3x3cut0r/docker/assets/26032621/e3664dee-ddf3-4e28-9234-214d3b04e2c7)
should be a simple fix!

**Comment by JeremiahSecrist** [comment]
i also got `Please install extra dependencies that are required for the EpubReader: pip install EbookLib html2text`

**Comment by JeremiahSecrist** [comment]
after closer inspection this is an upstream issue ill reference this issue there but there is a way to fix it on the compose side.

**Comment by 3x3cut0r** [comment]
i added the dependencies. pls try and report :D

**Comment by JeremiahSecrist** [comment]
that fixed the issue. thanks!
