### ISSUE TITLE
[privategpt] New image pull

### ISSUE THREAD

**Issue by dwesthead** [3x3cut0r/docker#5]
Hi,

Probably the way way we create our docs at work, but after pulling a new image today, I still get the error about needing docx2txt to ingest the document.

Works fine for PDF ... just not docx.

I have also tried rebuilding the image using the dockerfile from your github too.

It looks like it creates the image with no errors at all but if i try to deploy a container using that image, it comes up for a few seconds and then exits and the logs show a number of errors.

Am I doing something very silly or should i be able to just build the image with "docker build -t image2 ." and then use it with "docker run -p 8001:8080 image2" ?

The older image of yours works great and is nice and quick on responses ... i was just trying to get the latest one working and saw that it had the docx2txt in it !

Thanks.

Dean.

**Comment by 3x3cut0r** [comment]
> It looks like it creates the image with no errors at all but if i try to deploy a container using that image, it comes up for a few seconds and then exits and the logs show a number of errors.

would help to see the errors.

> Am I doing something very silly or should i be able to just build the image with "docker build -t image2 ." and then use it with "docker run -p 8001:8080 image2" ?

should work

> The older image of yours works great and is nice and quick on responses ... i was just trying to get the latest one working and saw that it had the docx2txt in it !

means it is working now? or do i need to add some other package?

**Comment by dwesthead** [comment]
Hi,

Forget the errors .... I think it was where i was mounting one of the volumes that it didnt like ! I have moved it to somewhere else and all the errors have stopped now so the container now starts.

I still get the docxttxt message when I try to upload a word docx file 

![image_2024-01-31_081438389](https://github.com/3x3cut0r/docker/assets/25345131/624a80f8-54c9-4d5b-a278-b5d39480fba4)

I have also changed the docker-entrypoint.sh a little so that it will read a file pointer for LOGO_SVG_BASE64 and not need the data entered directly into the variable.

It might be that i was doing something wrong but whenever i had a file listed as that environment variable it would fail to read it. Only when I entered the huge text string directly into it did it work.

The contain now builds and runs great so thanks for all your hard work on it !

If I can just get the docx upload to work .....

Dean.

**Comment by 3x3cut0r** [comment]
so i did some research and tested it locally. i figured out i did some mistake and installed the missing packages on the wrong pip environment. the last time i did not do some tests on that. so now it should work.
give my github-runner some time (like 1-2 hours) and then try again. should work now.

about the LOGO_SVG_BASE64. i did not want to replace the base64 thing, because that comes from the upstream project and i did not want to change it. so i will leave it as it is.

tell me if its is working now.

**Comment by dwesthead** [comment]
You are a hero !

Works perfect now.

Thanks for all your help.

Dean.

**Comment by 3x3cut0r** [comment]
you are welcome :)
